// TODO: add the rest
export const ERROR_CODES = {
  OUTPUT_VECTOR: 1,
  EXPECTED_FN_IDENT: 2,
  AST_MAX_STMNT_REACHED: 3,
  FN_CALL_EXCEEDED_CALLS: 4,
  FN_DEF_MISSING_END: 5,
  MISSING_PAREN: 6,
  EXPECTED_COMMA_PAREN: 7,
} as const;
